version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/microblog
    steps:
      - setup_remote_docker
      - checkout

      - run:
          name: Install-test dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install-test
      - run:
          name: Run the tests
          command: docker-compose up microblog-circleci

  push_to_dockerhub:
    environment:
      IMAGE_NAME: microblog
    docker:
    - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME -f docker/Dockerfile_prod .
      - run:
          name: Push to Dockerhub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/microblog:latest


workflows:
  test:
    jobs:
      - run_tests

  deploy:
    jobs:
      - push_to_dockerhub