FROM python:3.6-alpine

RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

# hadolint ignore=DL3013,DL3018
RUN apk --no-cache add --virtual build-dependencies libffi-dev openssl-dev py-pip build-base \
  && pip install --upgrade pip \
  && pip install  cryptography \
  && pip install -r requirements.txt \
  && apk del build-dependencies

RUN python -m venv .venv
ENV FLASK_APP microblog.py
# RUN .venv/bin/pip3 install -r requirements.txt

RUN chmod +x boot.sh

RUN chown -R microblog:microblog ./
USER microblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]

# WORKDIR /microblog


# COPY /app/ ./app/
# COPY /migrations/ ./migrations/
# COPY /requirements/ ./requirements/
# COPY requirements.txt ./

# RUN pip install --no-cache-dir -r requirements.txt

# CMD ["gunicorn", "-b 0.0.0.0:8000", "-w 4", "microblog:app"]